#!/bin/bash

# Colors

MAGENTA='\033[35m'
NC='\033[0m'
BOLD='\033[1m'


# Read input file line-by-line and parse whether the rotation should go up or down, then print the number of zeros passed over and landed on.

string="$HOME/aoc/2025/01-string.txt"
rotation=50
zeros=0

while IFS= read -r line; do
	char="${line:0:1}"
	num="${line:1}"

	# Determine step direction: +1 for R, -1 for L
	if [[ "$char" == "R" ]]; then
        step=1
    	elif [[ "$char" == "L" ]]; then
        step=-1
    	else
        continue
    	fi

    # Count zeros for each intermediate position
    	
    	for ((i=1; i<=num; i++)); do
        rotation=$(( (rotation + step + 100) % 100 ))
        	
		if (( rotation == 0 )); then
            		(( zeros++ ))
        	fi
    	done

done < "$string"

echo
echo -e "$BOLD The dial points at or passes over zero $MAGENTA$zeros$NC times."
echo

