#!/bin/bash


# Colors

NC='\e[0m'
MAGENTA='\e[35m'


#

naughty=("ab" "cd" "pq" "xy")
vowels=("a" "e" "i" "o" "u")
counter=0

while IFS= read -r line; do
	duplicates=$(echo "$line" | fold -w1 | sort | uniq -d)
#		[[ $line != *"$naughty"* ]] && [[ $line == *"$vowels"* ]] && [[ -n "$duplicates" ]]; then

	for pattern in "${naughty[@]}"; do
		if 
			[[ "$line" != *$pattern* ]]; then
			for pattern2 in "${vowels[@]}"; do
				if [[ "$line" == *$pattern2* ]]; then
				((counter++))
				echo "$counter"
				fi
			done
		fi
	done

done < "$HOME/advent-of-code/2015/05/05-string.txt"

echo -e "Answer: $MAGENTA$counter"
